---
title: "ARM"
output: html_document
date: "2023-03-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ARM

### 1. Data Loading

Dataset source: <https://www.kaggle.com/datasets/mathchi/online-retail-data-set-from-ml-repository>

```{r}
```

```{r}
library(arules)
library(arulesViz)
```

`{#retail = read.csv('./data/retail_dataset.csv')}`

```{r}

retail <- read.transactions("./data/retail_product_4.csv", format = "basket", sep = ",", skip = 1)
```

```{r}
retail
```

```{r}
#summary(retail)
```

```{r}
rule <- apriori(retail, parameter = list(support = 0.001, confidence = 0.2))
```

```{r}
inspect(head(rule, 25))
```

```{r}
inspect(head(sort(rule, by = "support"), 15))
```

```{r}
inspect(head(sort(rule, by = "confidence"), 15))
```

```{r}
inspect(head(sort(rule, by = "lift"), 15))
```

```{r}
png(filename="img/lift_15.png")
plot(head(sort(rule, by = "lift"), 15))
```

```{r}
png(filename="img/confidence_15.png")
plot(head(sort(rule, by = "confidence"), 15))
```

```{r}
png(filename="img/support_15.png")
plot(head(sort(rule, by = "support"), 15))
```

```{r}
plot(rule)
```

```{r}
png(filename="img/lift_15_group.png")
plot(head(sort(rule, by = "lift"), 15), method = "grouped")
```

```{r}
png(filename="img/confidencek_15_group.png")
plot(head(sort(rule, by = "confidence"), 15), method = "grouped")
```

```{r}
png(filename="img/support_15_group.png", width = 8, height = 4, units = 'in', res = 300)
plot(head(sort(rule, by = "support"), 15), method = "grouped")
```

```{r}
plot(rule, method = "grouped")
```

```{r}
rule2 <- apriori(retail, parameter = list(support = 0.02,
                                             confidence = 0.6))
```

```{r}
plot(rule2, method="grouped")

```
